using System;
using SpirVGraph.Spv;
using Toe.Scripting;

namespace SpirVGraph.NodeFactories
{
    public class SpvNodeRegistry: AbstractNodeRegistry
    {

        public OpNopNodeFactory OpNopNodeFactory;
        public OpUndefNodeFactory OpUndefNodeFactory;
        public OpSourceContinuedNodeFactory OpSourceContinuedNodeFactory;
        public OpSourceNodeFactory OpSourceNodeFactory;
        public OpSourceExtensionNodeFactory OpSourceExtensionNodeFactory;
        public OpNameNodeFactory OpNameNodeFactory;
        public OpMemberNameNodeFactory OpMemberNameNodeFactory;
        public OpStringNodeFactory OpStringNodeFactory;
        public OpLineNodeFactory OpLineNodeFactory;
        public OpExtensionNodeFactory OpExtensionNodeFactory;
        public OpExtInstImportNodeFactory OpExtInstImportNodeFactory;
        public OpExtInstNodeFactory OpExtInstNodeFactory;
        public OpMemoryModelNodeFactory OpMemoryModelNodeFactory;
        public OpEntryPointNodeFactory OpEntryPointNodeFactory;
        public OpExecutionModeNodeFactory OpExecutionModeNodeFactory;
        public OpCapabilityNodeFactory OpCapabilityNodeFactory;
        public OpTypeVoidNodeFactory OpTypeVoidNodeFactory;
        public OpTypeBoolNodeFactory OpTypeBoolNodeFactory;
        public OpTypeIntNodeFactory OpTypeIntNodeFactory;
        public OpTypeFloatNodeFactory OpTypeFloatNodeFactory;
        public OpTypeVectorNodeFactory OpTypeVectorNodeFactory;
        public OpTypeMatrixNodeFactory OpTypeMatrixNodeFactory;
        public OpTypeImageNodeFactory OpTypeImageNodeFactory;
        public OpTypeSamplerNodeFactory OpTypeSamplerNodeFactory;
        public OpTypeSampledImageNodeFactory OpTypeSampledImageNodeFactory;
        public OpTypeArrayNodeFactory OpTypeArrayNodeFactory;
        public OpTypeRuntimeArrayNodeFactory OpTypeRuntimeArrayNodeFactory;
        public OpTypeStructNodeFactory OpTypeStructNodeFactory;
        public OpTypeOpaqueNodeFactory OpTypeOpaqueNodeFactory;
        public OpTypePointerNodeFactory OpTypePointerNodeFactory;
        public OpTypeFunctionNodeFactory OpTypeFunctionNodeFactory;
        public OpTypeEventNodeFactory OpTypeEventNodeFactory;
        public OpTypeDeviceEventNodeFactory OpTypeDeviceEventNodeFactory;
        public OpTypeReserveIdNodeFactory OpTypeReserveIdNodeFactory;
        public OpTypeQueueNodeFactory OpTypeQueueNodeFactory;
        public OpTypePipeNodeFactory OpTypePipeNodeFactory;
        public OpTypeForwardPointerNodeFactory OpTypeForwardPointerNodeFactory;
        public OpConstantTrueNodeFactory OpConstantTrueNodeFactory;
        public OpConstantFalseNodeFactory OpConstantFalseNodeFactory;
        public OpConstantNodeFactory OpConstantNodeFactory;
        public OpConstantCompositeNodeFactory OpConstantCompositeNodeFactory;
        public OpConstantSamplerNodeFactory OpConstantSamplerNodeFactory;
        public OpConstantNullNodeFactory OpConstantNullNodeFactory;
        public OpSpecConstantTrueNodeFactory OpSpecConstantTrueNodeFactory;
        public OpSpecConstantFalseNodeFactory OpSpecConstantFalseNodeFactory;
        public OpSpecConstantNodeFactory OpSpecConstantNodeFactory;
        public OpSpecConstantCompositeNodeFactory OpSpecConstantCompositeNodeFactory;
        public OpSpecConstantOpNodeFactory OpSpecConstantOpNodeFactory;
        public OpFunctionNodeFactory OpFunctionNodeFactory;
        public OpFunctionParameterNodeFactory OpFunctionParameterNodeFactory;
        public OpFunctionEndNodeFactory OpFunctionEndNodeFactory;
        public OpFunctionCallNodeFactory OpFunctionCallNodeFactory;
        public OpVariableNodeFactory OpVariableNodeFactory;
        public OpImageTexelPointerNodeFactory OpImageTexelPointerNodeFactory;
        public OpLoadNodeFactory OpLoadNodeFactory;
        public OpStoreNodeFactory OpStoreNodeFactory;
        public OpCopyMemoryNodeFactory OpCopyMemoryNodeFactory;
        public OpCopyMemorySizedNodeFactory OpCopyMemorySizedNodeFactory;
        public OpAccessChainNodeFactory OpAccessChainNodeFactory;
        public OpInBoundsAccessChainNodeFactory OpInBoundsAccessChainNodeFactory;
        public OpPtrAccessChainNodeFactory OpPtrAccessChainNodeFactory;
        public OpArrayLengthNodeFactory OpArrayLengthNodeFactory;
        public OpGenericPtrMemSemanticsNodeFactory OpGenericPtrMemSemanticsNodeFactory;
        public OpInBoundsPtrAccessChainNodeFactory OpInBoundsPtrAccessChainNodeFactory;
        public OpDecorateNodeFactory OpDecorateNodeFactory;
        public OpMemberDecorateNodeFactory OpMemberDecorateNodeFactory;
        public OpDecorationGroupNodeFactory OpDecorationGroupNodeFactory;
        public OpGroupDecorateNodeFactory OpGroupDecorateNodeFactory;
        public OpGroupMemberDecorateNodeFactory OpGroupMemberDecorateNodeFactory;
        public OpVectorExtractDynamicNodeFactory OpVectorExtractDynamicNodeFactory;
        public OpVectorInsertDynamicNodeFactory OpVectorInsertDynamicNodeFactory;
        public OpVectorShuffleNodeFactory OpVectorShuffleNodeFactory;
        public OpCompositeConstructNodeFactory OpCompositeConstructNodeFactory;
        public OpCompositeExtractNodeFactory OpCompositeExtractNodeFactory;
        public OpCompositeInsertNodeFactory OpCompositeInsertNodeFactory;
        public OpCopyObjectNodeFactory OpCopyObjectNodeFactory;
        public OpTransposeNodeFactory OpTransposeNodeFactory;
        public OpSampledImageNodeFactory OpSampledImageNodeFactory;
        public OpImageSampleImplicitLodNodeFactory OpImageSampleImplicitLodNodeFactory;
        public OpImageSampleExplicitLodNodeFactory OpImageSampleExplicitLodNodeFactory;
        public OpImageSampleDrefImplicitLodNodeFactory OpImageSampleDrefImplicitLodNodeFactory;
        public OpImageSampleDrefExplicitLodNodeFactory OpImageSampleDrefExplicitLodNodeFactory;
        public OpImageSampleProjImplicitLodNodeFactory OpImageSampleProjImplicitLodNodeFactory;
        public OpImageSampleProjExplicitLodNodeFactory OpImageSampleProjExplicitLodNodeFactory;
        public OpImageSampleProjDrefImplicitLodNodeFactory OpImageSampleProjDrefImplicitLodNodeFactory;
        public OpImageSampleProjDrefExplicitLodNodeFactory OpImageSampleProjDrefExplicitLodNodeFactory;
        public OpImageFetchNodeFactory OpImageFetchNodeFactory;
        public OpImageGatherNodeFactory OpImageGatherNodeFactory;
        public OpImageDrefGatherNodeFactory OpImageDrefGatherNodeFactory;
        public OpImageReadNodeFactory OpImageReadNodeFactory;
        public OpImageWriteNodeFactory OpImageWriteNodeFactory;
        public OpImageNodeFactory OpImageNodeFactory;
        public OpImageQueryFormatNodeFactory OpImageQueryFormatNodeFactory;
        public OpImageQueryOrderNodeFactory OpImageQueryOrderNodeFactory;
        public OpImageQuerySizeLodNodeFactory OpImageQuerySizeLodNodeFactory;
        public OpImageQuerySizeNodeFactory OpImageQuerySizeNodeFactory;
        public OpImageQueryLodNodeFactory OpImageQueryLodNodeFactory;
        public OpImageQueryLevelsNodeFactory OpImageQueryLevelsNodeFactory;
        public OpImageQuerySamplesNodeFactory OpImageQuerySamplesNodeFactory;
        public OpConvertFToUNodeFactory OpConvertFToUNodeFactory;
        public OpConvertFToSNodeFactory OpConvertFToSNodeFactory;
        public OpConvertSToFNodeFactory OpConvertSToFNodeFactory;
        public OpConvertUToFNodeFactory OpConvertUToFNodeFactory;
        public OpUConvertNodeFactory OpUConvertNodeFactory;
        public OpSConvertNodeFactory OpSConvertNodeFactory;
        public OpFConvertNodeFactory OpFConvertNodeFactory;
        public OpQuantizeToF16NodeFactory OpQuantizeToF16NodeFactory;
        public OpConvertPtrToUNodeFactory OpConvertPtrToUNodeFactory;
        public OpSatConvertSToUNodeFactory OpSatConvertSToUNodeFactory;
        public OpSatConvertUToSNodeFactory OpSatConvertUToSNodeFactory;
        public OpConvertUToPtrNodeFactory OpConvertUToPtrNodeFactory;
        public OpPtrCastToGenericNodeFactory OpPtrCastToGenericNodeFactory;
        public OpGenericCastToPtrNodeFactory OpGenericCastToPtrNodeFactory;
        public OpGenericCastToPtrExplicitNodeFactory OpGenericCastToPtrExplicitNodeFactory;
        public OpBitcastNodeFactory OpBitcastNodeFactory;
        public OpSNegateNodeFactory OpSNegateNodeFactory;
        public OpFNegateNodeFactory OpFNegateNodeFactory;
        public OpIAddNodeFactory OpIAddNodeFactory;
        public OpFAddNodeFactory OpFAddNodeFactory;
        public OpISubNodeFactory OpISubNodeFactory;
        public OpFSubNodeFactory OpFSubNodeFactory;
        public OpIMulNodeFactory OpIMulNodeFactory;
        public OpFMulNodeFactory OpFMulNodeFactory;
        public OpUDivNodeFactory OpUDivNodeFactory;
        public OpSDivNodeFactory OpSDivNodeFactory;
        public OpFDivNodeFactory OpFDivNodeFactory;
        public OpUModNodeFactory OpUModNodeFactory;
        public OpSRemNodeFactory OpSRemNodeFactory;
        public OpSModNodeFactory OpSModNodeFactory;
        public OpFRemNodeFactory OpFRemNodeFactory;
        public OpFModNodeFactory OpFModNodeFactory;
        public OpVectorTimesScalarNodeFactory OpVectorTimesScalarNodeFactory;
        public OpMatrixTimesScalarNodeFactory OpMatrixTimesScalarNodeFactory;
        public OpVectorTimesMatrixNodeFactory OpVectorTimesMatrixNodeFactory;
        public OpMatrixTimesVectorNodeFactory OpMatrixTimesVectorNodeFactory;
        public OpMatrixTimesMatrixNodeFactory OpMatrixTimesMatrixNodeFactory;
        public OpOuterProductNodeFactory OpOuterProductNodeFactory;
        public OpDotNodeFactory OpDotNodeFactory;
        public OpIAddCarryNodeFactory OpIAddCarryNodeFactory;
        public OpISubBorrowNodeFactory OpISubBorrowNodeFactory;
        public OpUMulExtendedNodeFactory OpUMulExtendedNodeFactory;
        public OpSMulExtendedNodeFactory OpSMulExtendedNodeFactory;
        public OpAnyNodeFactory OpAnyNodeFactory;
        public OpAllNodeFactory OpAllNodeFactory;
        public OpIsNanNodeFactory OpIsNanNodeFactory;
        public OpIsInfNodeFactory OpIsInfNodeFactory;
        public OpIsFiniteNodeFactory OpIsFiniteNodeFactory;
        public OpIsNormalNodeFactory OpIsNormalNodeFactory;
        public OpSignBitSetNodeFactory OpSignBitSetNodeFactory;
        public OpLessOrGreaterNodeFactory OpLessOrGreaterNodeFactory;
        public OpOrderedNodeFactory OpOrderedNodeFactory;
        public OpUnorderedNodeFactory OpUnorderedNodeFactory;
        public OpLogicalEqualNodeFactory OpLogicalEqualNodeFactory;
        public OpLogicalNotEqualNodeFactory OpLogicalNotEqualNodeFactory;
        public OpLogicalOrNodeFactory OpLogicalOrNodeFactory;
        public OpLogicalAndNodeFactory OpLogicalAndNodeFactory;
        public OpLogicalNotNodeFactory OpLogicalNotNodeFactory;
        public OpSelectNodeFactory OpSelectNodeFactory;
        public OpIEqualNodeFactory OpIEqualNodeFactory;
        public OpINotEqualNodeFactory OpINotEqualNodeFactory;
        public OpUGreaterThanNodeFactory OpUGreaterThanNodeFactory;
        public OpSGreaterThanNodeFactory OpSGreaterThanNodeFactory;
        public OpUGreaterThanEqualNodeFactory OpUGreaterThanEqualNodeFactory;
        public OpSGreaterThanEqualNodeFactory OpSGreaterThanEqualNodeFactory;
        public OpULessThanNodeFactory OpULessThanNodeFactory;
        public OpSLessThanNodeFactory OpSLessThanNodeFactory;
        public OpULessThanEqualNodeFactory OpULessThanEqualNodeFactory;
        public OpSLessThanEqualNodeFactory OpSLessThanEqualNodeFactory;
        public OpFOrdEqualNodeFactory OpFOrdEqualNodeFactory;
        public OpFUnordEqualNodeFactory OpFUnordEqualNodeFactory;
        public OpFOrdNotEqualNodeFactory OpFOrdNotEqualNodeFactory;
        public OpFUnordNotEqualNodeFactory OpFUnordNotEqualNodeFactory;
        public OpFOrdLessThanNodeFactory OpFOrdLessThanNodeFactory;
        public OpFUnordLessThanNodeFactory OpFUnordLessThanNodeFactory;
        public OpFOrdGreaterThanNodeFactory OpFOrdGreaterThanNodeFactory;
        public OpFUnordGreaterThanNodeFactory OpFUnordGreaterThanNodeFactory;
        public OpFOrdLessThanEqualNodeFactory OpFOrdLessThanEqualNodeFactory;
        public OpFUnordLessThanEqualNodeFactory OpFUnordLessThanEqualNodeFactory;
        public OpFOrdGreaterThanEqualNodeFactory OpFOrdGreaterThanEqualNodeFactory;
        public OpFUnordGreaterThanEqualNodeFactory OpFUnordGreaterThanEqualNodeFactory;
        public OpShiftRightLogicalNodeFactory OpShiftRightLogicalNodeFactory;
        public OpShiftRightArithmeticNodeFactory OpShiftRightArithmeticNodeFactory;
        public OpShiftLeftLogicalNodeFactory OpShiftLeftLogicalNodeFactory;
        public OpBitwiseOrNodeFactory OpBitwiseOrNodeFactory;
        public OpBitwiseXorNodeFactory OpBitwiseXorNodeFactory;
        public OpBitwiseAndNodeFactory OpBitwiseAndNodeFactory;
        public OpNotNodeFactory OpNotNodeFactory;
        public OpBitFieldInsertNodeFactory OpBitFieldInsertNodeFactory;
        public OpBitFieldSExtractNodeFactory OpBitFieldSExtractNodeFactory;
        public OpBitFieldUExtractNodeFactory OpBitFieldUExtractNodeFactory;
        public OpBitReverseNodeFactory OpBitReverseNodeFactory;
        public OpBitCountNodeFactory OpBitCountNodeFactory;
        public OpDPdxNodeFactory OpDPdxNodeFactory;
        public OpDPdyNodeFactory OpDPdyNodeFactory;
        public OpFwidthNodeFactory OpFwidthNodeFactory;
        public OpDPdxFineNodeFactory OpDPdxFineNodeFactory;
        public OpDPdyFineNodeFactory OpDPdyFineNodeFactory;
        public OpFwidthFineNodeFactory OpFwidthFineNodeFactory;
        public OpDPdxCoarseNodeFactory OpDPdxCoarseNodeFactory;
        public OpDPdyCoarseNodeFactory OpDPdyCoarseNodeFactory;
        public OpFwidthCoarseNodeFactory OpFwidthCoarseNodeFactory;
        public OpEmitVertexNodeFactory OpEmitVertexNodeFactory;
        public OpEndPrimitiveNodeFactory OpEndPrimitiveNodeFactory;
        public OpEmitStreamVertexNodeFactory OpEmitStreamVertexNodeFactory;
        public OpEndStreamPrimitiveNodeFactory OpEndStreamPrimitiveNodeFactory;
        public OpControlBarrierNodeFactory OpControlBarrierNodeFactory;
        public OpMemoryBarrierNodeFactory OpMemoryBarrierNodeFactory;
        public OpAtomicLoadNodeFactory OpAtomicLoadNodeFactory;
        public OpAtomicStoreNodeFactory OpAtomicStoreNodeFactory;
        public OpAtomicExchangeNodeFactory OpAtomicExchangeNodeFactory;
        public OpAtomicCompareExchangeNodeFactory OpAtomicCompareExchangeNodeFactory;
        public OpAtomicCompareExchangeWeakNodeFactory OpAtomicCompareExchangeWeakNodeFactory;
        public OpAtomicIIncrementNodeFactory OpAtomicIIncrementNodeFactory;
        public OpAtomicIDecrementNodeFactory OpAtomicIDecrementNodeFactory;
        public OpAtomicIAddNodeFactory OpAtomicIAddNodeFactory;
        public OpAtomicISubNodeFactory OpAtomicISubNodeFactory;
        public OpAtomicSMinNodeFactory OpAtomicSMinNodeFactory;
        public OpAtomicUMinNodeFactory OpAtomicUMinNodeFactory;
        public OpAtomicSMaxNodeFactory OpAtomicSMaxNodeFactory;
        public OpAtomicUMaxNodeFactory OpAtomicUMaxNodeFactory;
        public OpAtomicAndNodeFactory OpAtomicAndNodeFactory;
        public OpAtomicOrNodeFactory OpAtomicOrNodeFactory;
        public OpAtomicXorNodeFactory OpAtomicXorNodeFactory;
        public OpPhiNodeFactory OpPhiNodeFactory;
        public OpLoopMergeNodeFactory OpLoopMergeNodeFactory;
        public OpSelectionMergeNodeFactory OpSelectionMergeNodeFactory;
        public OpLabelNodeFactory OpLabelNodeFactory;
        public OpBranchNodeFactory OpBranchNodeFactory;
        public OpBranchConditionalNodeFactory OpBranchConditionalNodeFactory;
        public OpSwitchNodeFactory OpSwitchNodeFactory;
        public OpKillNodeFactory OpKillNodeFactory;
        public OpReturnNodeFactory OpReturnNodeFactory;
        public OpReturnValueNodeFactory OpReturnValueNodeFactory;
        public OpUnreachableNodeFactory OpUnreachableNodeFactory;
        public OpLifetimeStartNodeFactory OpLifetimeStartNodeFactory;
        public OpLifetimeStopNodeFactory OpLifetimeStopNodeFactory;
        public OpGroupAsyncCopyNodeFactory OpGroupAsyncCopyNodeFactory;
        public OpGroupWaitEventsNodeFactory OpGroupWaitEventsNodeFactory;
        public OpGroupAllNodeFactory OpGroupAllNodeFactory;
        public OpGroupAnyNodeFactory OpGroupAnyNodeFactory;
        public OpGroupBroadcastNodeFactory OpGroupBroadcastNodeFactory;
        public OpGroupIAddNodeFactory OpGroupIAddNodeFactory;
        public OpGroupFAddNodeFactory OpGroupFAddNodeFactory;
        public OpGroupFMinNodeFactory OpGroupFMinNodeFactory;
        public OpGroupUMinNodeFactory OpGroupUMinNodeFactory;
        public OpGroupSMinNodeFactory OpGroupSMinNodeFactory;
        public OpGroupFMaxNodeFactory OpGroupFMaxNodeFactory;
        public OpGroupUMaxNodeFactory OpGroupUMaxNodeFactory;
        public OpGroupSMaxNodeFactory OpGroupSMaxNodeFactory;
        public OpReadPipeNodeFactory OpReadPipeNodeFactory;
        public OpWritePipeNodeFactory OpWritePipeNodeFactory;
        public OpReservedReadPipeNodeFactory OpReservedReadPipeNodeFactory;
        public OpReservedWritePipeNodeFactory OpReservedWritePipeNodeFactory;
        public OpReserveReadPipePacketsNodeFactory OpReserveReadPipePacketsNodeFactory;
        public OpReserveWritePipePacketsNodeFactory OpReserveWritePipePacketsNodeFactory;
        public OpCommitReadPipeNodeFactory OpCommitReadPipeNodeFactory;
        public OpCommitWritePipeNodeFactory OpCommitWritePipeNodeFactory;
        public OpIsValidReserveIdNodeFactory OpIsValidReserveIdNodeFactory;
        public OpGetNumPipePacketsNodeFactory OpGetNumPipePacketsNodeFactory;
        public OpGetMaxPipePacketsNodeFactory OpGetMaxPipePacketsNodeFactory;
        public OpGroupReserveReadPipePacketsNodeFactory OpGroupReserveReadPipePacketsNodeFactory;
        public OpGroupReserveWritePipePacketsNodeFactory OpGroupReserveWritePipePacketsNodeFactory;
        public OpGroupCommitReadPipeNodeFactory OpGroupCommitReadPipeNodeFactory;
        public OpGroupCommitWritePipeNodeFactory OpGroupCommitWritePipeNodeFactory;
        public OpEnqueueMarkerNodeFactory OpEnqueueMarkerNodeFactory;
        public OpEnqueueKernelNodeFactory OpEnqueueKernelNodeFactory;
        public OpGetKernelNDrangeSubGroupCountNodeFactory OpGetKernelNDrangeSubGroupCountNodeFactory;
        public OpGetKernelNDrangeMaxSubGroupSizeNodeFactory OpGetKernelNDrangeMaxSubGroupSizeNodeFactory;
        public OpGetKernelWorkGroupSizeNodeFactory OpGetKernelWorkGroupSizeNodeFactory;
        public OpGetKernelPreferredWorkGroupSizeMultipleNodeFactory OpGetKernelPreferredWorkGroupSizeMultipleNodeFactory;
        public OpRetainEventNodeFactory OpRetainEventNodeFactory;
        public OpReleaseEventNodeFactory OpReleaseEventNodeFactory;
        public OpCreateUserEventNodeFactory OpCreateUserEventNodeFactory;
        public OpIsValidEventNodeFactory OpIsValidEventNodeFactory;
        public OpSetUserEventStatusNodeFactory OpSetUserEventStatusNodeFactory;
        public OpCaptureEventProfilingInfoNodeFactory OpCaptureEventProfilingInfoNodeFactory;
        public OpGetDefaultQueueNodeFactory OpGetDefaultQueueNodeFactory;
        public OpBuildNDRangeNodeFactory OpBuildNDRangeNodeFactory;
        public OpImageSparseSampleImplicitLodNodeFactory OpImageSparseSampleImplicitLodNodeFactory;
        public OpImageSparseSampleExplicitLodNodeFactory OpImageSparseSampleExplicitLodNodeFactory;
        public OpImageSparseSampleDrefImplicitLodNodeFactory OpImageSparseSampleDrefImplicitLodNodeFactory;
        public OpImageSparseSampleDrefExplicitLodNodeFactory OpImageSparseSampleDrefExplicitLodNodeFactory;
        public OpImageSparseSampleProjImplicitLodNodeFactory OpImageSparseSampleProjImplicitLodNodeFactory;
        public OpImageSparseSampleProjExplicitLodNodeFactory OpImageSparseSampleProjExplicitLodNodeFactory;
        public OpImageSparseSampleProjDrefImplicitLodNodeFactory OpImageSparseSampleProjDrefImplicitLodNodeFactory;
        public OpImageSparseSampleProjDrefExplicitLodNodeFactory OpImageSparseSampleProjDrefExplicitLodNodeFactory;
        public OpImageSparseFetchNodeFactory OpImageSparseFetchNodeFactory;
        public OpImageSparseGatherNodeFactory OpImageSparseGatherNodeFactory;
        public OpImageSparseDrefGatherNodeFactory OpImageSparseDrefGatherNodeFactory;
        public OpImageSparseTexelsResidentNodeFactory OpImageSparseTexelsResidentNodeFactory;
        public OpNoLineNodeFactory OpNoLineNodeFactory;
        public OpAtomicFlagTestAndSetNodeFactory OpAtomicFlagTestAndSetNodeFactory;
        public OpAtomicFlagClearNodeFactory OpAtomicFlagClearNodeFactory;
        public OpImageSparseReadNodeFactory OpImageSparseReadNodeFactory;
        public OpDecorateIdNodeFactory OpDecorateIdNodeFactory;
        public OpSubgroupBallotKHRNodeFactory OpSubgroupBallotKHRNodeFactory;
        public OpSubgroupFirstInvocationKHRNodeFactory OpSubgroupFirstInvocationKHRNodeFactory;
        public OpSubgroupAllKHRNodeFactory OpSubgroupAllKHRNodeFactory;
        public OpSubgroupAnyKHRNodeFactory OpSubgroupAnyKHRNodeFactory;
        public OpSubgroupAllEqualKHRNodeFactory OpSubgroupAllEqualKHRNodeFactory;
        public OpSubgroupReadInvocationKHRNodeFactory OpSubgroupReadInvocationKHRNodeFactory;
        public OpGroupIAddNonUniformAMDNodeFactory OpGroupIAddNonUniformAMDNodeFactory;
        public OpGroupFAddNonUniformAMDNodeFactory OpGroupFAddNonUniformAMDNodeFactory;
        public OpGroupFMinNonUniformAMDNodeFactory OpGroupFMinNonUniformAMDNodeFactory;
        public OpGroupUMinNonUniformAMDNodeFactory OpGroupUMinNonUniformAMDNodeFactory;
        public OpGroupSMinNonUniformAMDNodeFactory OpGroupSMinNonUniformAMDNodeFactory;
        public OpGroupFMaxNonUniformAMDNodeFactory OpGroupFMaxNonUniformAMDNodeFactory;
        public OpGroupUMaxNonUniformAMDNodeFactory OpGroupUMaxNonUniformAMDNodeFactory;
        public OpGroupSMaxNonUniformAMDNodeFactory OpGroupSMaxNonUniformAMDNodeFactory;
        public OpFragmentMaskFetchAMDNodeFactory OpFragmentMaskFetchAMDNodeFactory;
        public OpFragmentFetchAMDNodeFactory OpFragmentFetchAMDNodeFactory;
        public OpSubgroupShuffleINTELNodeFactory OpSubgroupShuffleINTELNodeFactory;
        public OpSubgroupShuffleDownINTELNodeFactory OpSubgroupShuffleDownINTELNodeFactory;
        public OpSubgroupShuffleUpINTELNodeFactory OpSubgroupShuffleUpINTELNodeFactory;
        public OpSubgroupShuffleXorINTELNodeFactory OpSubgroupShuffleXorINTELNodeFactory;
        public OpSubgroupBlockReadINTELNodeFactory OpSubgroupBlockReadINTELNodeFactory;
        public OpSubgroupBlockWriteINTELNodeFactory OpSubgroupBlockWriteINTELNodeFactory;
        public OpSubgroupImageBlockReadINTELNodeFactory OpSubgroupImageBlockReadINTELNodeFactory;
        public OpSubgroupImageBlockWriteINTELNodeFactory OpSubgroupImageBlockWriteINTELNodeFactory;
        public OpDecorateStringGOOGLENodeFactory OpDecorateStringGOOGLENodeFactory;
        public OpMemberDecorateStringGOOGLENodeFactory OpMemberDecorateStringGOOGLENodeFactory;

        public SpvNodeRegistry()
        {

            Add(OpNopNodeFactory = new OpNopNodeFactory());
            Add(OpUndefNodeFactory = new OpUndefNodeFactory());
            Add(OpSourceContinuedNodeFactory = new OpSourceContinuedNodeFactory());
            Add(OpSourceNodeFactory = new OpSourceNodeFactory());
            Add(OpSourceExtensionNodeFactory = new OpSourceExtensionNodeFactory());
            Add(OpNameNodeFactory = new OpNameNodeFactory());
            Add(OpMemberNameNodeFactory = new OpMemberNameNodeFactory());
            Add(OpStringNodeFactory = new OpStringNodeFactory());
            Add(OpLineNodeFactory = new OpLineNodeFactory());
            Add(OpExtensionNodeFactory = new OpExtensionNodeFactory());
            Add(OpExtInstImportNodeFactory = new OpExtInstImportNodeFactory());
            Add(OpExtInstNodeFactory = new OpExtInstNodeFactory());
            Add(OpMemoryModelNodeFactory = new OpMemoryModelNodeFactory());
            Add(OpEntryPointNodeFactory = new OpEntryPointNodeFactory());
            Add(OpExecutionModeNodeFactory = new OpExecutionModeNodeFactory());
            Add(OpCapabilityNodeFactory = new OpCapabilityNodeFactory());
            Add(OpTypeVoidNodeFactory = new OpTypeVoidNodeFactory());
            Add(OpTypeBoolNodeFactory = new OpTypeBoolNodeFactory());
            Add(OpTypeIntNodeFactory = new OpTypeIntNodeFactory());
            Add(OpTypeFloatNodeFactory = new OpTypeFloatNodeFactory());
            Add(OpTypeVectorNodeFactory = new OpTypeVectorNodeFactory());
            Add(OpTypeMatrixNodeFactory = new OpTypeMatrixNodeFactory());
            Add(OpTypeImageNodeFactory = new OpTypeImageNodeFactory());
            Add(OpTypeSamplerNodeFactory = new OpTypeSamplerNodeFactory());
            Add(OpTypeSampledImageNodeFactory = new OpTypeSampledImageNodeFactory());
            Add(OpTypeArrayNodeFactory = new OpTypeArrayNodeFactory());
            Add(OpTypeRuntimeArrayNodeFactory = new OpTypeRuntimeArrayNodeFactory());
            Add(OpTypeStructNodeFactory = new OpTypeStructNodeFactory());
            Add(OpTypeOpaqueNodeFactory = new OpTypeOpaqueNodeFactory());
            Add(OpTypePointerNodeFactory = new OpTypePointerNodeFactory());
            Add(OpTypeFunctionNodeFactory = new OpTypeFunctionNodeFactory());
            Add(OpTypeEventNodeFactory = new OpTypeEventNodeFactory());
            Add(OpTypeDeviceEventNodeFactory = new OpTypeDeviceEventNodeFactory());
            Add(OpTypeReserveIdNodeFactory = new OpTypeReserveIdNodeFactory());
            Add(OpTypeQueueNodeFactory = new OpTypeQueueNodeFactory());
            Add(OpTypePipeNodeFactory = new OpTypePipeNodeFactory());
            Add(OpTypeForwardPointerNodeFactory = new OpTypeForwardPointerNodeFactory());
            Add(OpConstantTrueNodeFactory = new OpConstantTrueNodeFactory());
            Add(OpConstantFalseNodeFactory = new OpConstantFalseNodeFactory());
            Add(OpConstantNodeFactory = new OpConstantNodeFactory());
            Add(OpConstantCompositeNodeFactory = new OpConstantCompositeNodeFactory());
            Add(OpConstantSamplerNodeFactory = new OpConstantSamplerNodeFactory());
            Add(OpConstantNullNodeFactory = new OpConstantNullNodeFactory());
            Add(OpSpecConstantTrueNodeFactory = new OpSpecConstantTrueNodeFactory());
            Add(OpSpecConstantFalseNodeFactory = new OpSpecConstantFalseNodeFactory());
            Add(OpSpecConstantNodeFactory = new OpSpecConstantNodeFactory());
            Add(OpSpecConstantCompositeNodeFactory = new OpSpecConstantCompositeNodeFactory());
            Add(OpSpecConstantOpNodeFactory = new OpSpecConstantOpNodeFactory());
            Add(OpFunctionNodeFactory = new OpFunctionNodeFactory());
            Add(OpFunctionParameterNodeFactory = new OpFunctionParameterNodeFactory());
            Add(OpFunctionEndNodeFactory = new OpFunctionEndNodeFactory());
            Add(OpFunctionCallNodeFactory = new OpFunctionCallNodeFactory());
            Add(OpVariableNodeFactory = new OpVariableNodeFactory());
            Add(OpImageTexelPointerNodeFactory = new OpImageTexelPointerNodeFactory());
            Add(OpLoadNodeFactory = new OpLoadNodeFactory());
            Add(OpStoreNodeFactory = new OpStoreNodeFactory());
            Add(OpCopyMemoryNodeFactory = new OpCopyMemoryNodeFactory());
            Add(OpCopyMemorySizedNodeFactory = new OpCopyMemorySizedNodeFactory());
            Add(OpAccessChainNodeFactory = new OpAccessChainNodeFactory());
            Add(OpInBoundsAccessChainNodeFactory = new OpInBoundsAccessChainNodeFactory());
            Add(OpPtrAccessChainNodeFactory = new OpPtrAccessChainNodeFactory());
            Add(OpArrayLengthNodeFactory = new OpArrayLengthNodeFactory());
            Add(OpGenericPtrMemSemanticsNodeFactory = new OpGenericPtrMemSemanticsNodeFactory());
            Add(OpInBoundsPtrAccessChainNodeFactory = new OpInBoundsPtrAccessChainNodeFactory());
            Add(OpDecorateNodeFactory = new OpDecorateNodeFactory());
            Add(OpMemberDecorateNodeFactory = new OpMemberDecorateNodeFactory());
            Add(OpDecorationGroupNodeFactory = new OpDecorationGroupNodeFactory());
            Add(OpGroupDecorateNodeFactory = new OpGroupDecorateNodeFactory());
            Add(OpGroupMemberDecorateNodeFactory = new OpGroupMemberDecorateNodeFactory());
            Add(OpVectorExtractDynamicNodeFactory = new OpVectorExtractDynamicNodeFactory());
            Add(OpVectorInsertDynamicNodeFactory = new OpVectorInsertDynamicNodeFactory());
            Add(OpVectorShuffleNodeFactory = new OpVectorShuffleNodeFactory());
            Add(OpCompositeConstructNodeFactory = new OpCompositeConstructNodeFactory());
            Add(OpCompositeExtractNodeFactory = new OpCompositeExtractNodeFactory());
            Add(OpCompositeInsertNodeFactory = new OpCompositeInsertNodeFactory());
            Add(OpCopyObjectNodeFactory = new OpCopyObjectNodeFactory());
            Add(OpTransposeNodeFactory = new OpTransposeNodeFactory());
            Add(OpSampledImageNodeFactory = new OpSampledImageNodeFactory());
            Add(OpImageSampleImplicitLodNodeFactory = new OpImageSampleImplicitLodNodeFactory());
            Add(OpImageSampleExplicitLodNodeFactory = new OpImageSampleExplicitLodNodeFactory());
            Add(OpImageSampleDrefImplicitLodNodeFactory = new OpImageSampleDrefImplicitLodNodeFactory());
            Add(OpImageSampleDrefExplicitLodNodeFactory = new OpImageSampleDrefExplicitLodNodeFactory());
            Add(OpImageSampleProjImplicitLodNodeFactory = new OpImageSampleProjImplicitLodNodeFactory());
            Add(OpImageSampleProjExplicitLodNodeFactory = new OpImageSampleProjExplicitLodNodeFactory());
            Add(OpImageSampleProjDrefImplicitLodNodeFactory = new OpImageSampleProjDrefImplicitLodNodeFactory());
            Add(OpImageSampleProjDrefExplicitLodNodeFactory = new OpImageSampleProjDrefExplicitLodNodeFactory());
            Add(OpImageFetchNodeFactory = new OpImageFetchNodeFactory());
            Add(OpImageGatherNodeFactory = new OpImageGatherNodeFactory());
            Add(OpImageDrefGatherNodeFactory = new OpImageDrefGatherNodeFactory());
            Add(OpImageReadNodeFactory = new OpImageReadNodeFactory());
            Add(OpImageWriteNodeFactory = new OpImageWriteNodeFactory());
            Add(OpImageNodeFactory = new OpImageNodeFactory());
            Add(OpImageQueryFormatNodeFactory = new OpImageQueryFormatNodeFactory());
            Add(OpImageQueryOrderNodeFactory = new OpImageQueryOrderNodeFactory());
            Add(OpImageQuerySizeLodNodeFactory = new OpImageQuerySizeLodNodeFactory());
            Add(OpImageQuerySizeNodeFactory = new OpImageQuerySizeNodeFactory());
            Add(OpImageQueryLodNodeFactory = new OpImageQueryLodNodeFactory());
            Add(OpImageQueryLevelsNodeFactory = new OpImageQueryLevelsNodeFactory());
            Add(OpImageQuerySamplesNodeFactory = new OpImageQuerySamplesNodeFactory());
            Add(OpConvertFToUNodeFactory = new OpConvertFToUNodeFactory());
            Add(OpConvertFToSNodeFactory = new OpConvertFToSNodeFactory());
            Add(OpConvertSToFNodeFactory = new OpConvertSToFNodeFactory());
            Add(OpConvertUToFNodeFactory = new OpConvertUToFNodeFactory());
            Add(OpUConvertNodeFactory = new OpUConvertNodeFactory());
            Add(OpSConvertNodeFactory = new OpSConvertNodeFactory());
            Add(OpFConvertNodeFactory = new OpFConvertNodeFactory());
            Add(OpQuantizeToF16NodeFactory = new OpQuantizeToF16NodeFactory());
            Add(OpConvertPtrToUNodeFactory = new OpConvertPtrToUNodeFactory());
            Add(OpSatConvertSToUNodeFactory = new OpSatConvertSToUNodeFactory());
            Add(OpSatConvertUToSNodeFactory = new OpSatConvertUToSNodeFactory());
            Add(OpConvertUToPtrNodeFactory = new OpConvertUToPtrNodeFactory());
            Add(OpPtrCastToGenericNodeFactory = new OpPtrCastToGenericNodeFactory());
            Add(OpGenericCastToPtrNodeFactory = new OpGenericCastToPtrNodeFactory());
            Add(OpGenericCastToPtrExplicitNodeFactory = new OpGenericCastToPtrExplicitNodeFactory());
            Add(OpBitcastNodeFactory = new OpBitcastNodeFactory());
            Add(OpSNegateNodeFactory = new OpSNegateNodeFactory());
            Add(OpFNegateNodeFactory = new OpFNegateNodeFactory());
            Add(OpIAddNodeFactory = new OpIAddNodeFactory());
            Add(OpFAddNodeFactory = new OpFAddNodeFactory());
            Add(OpISubNodeFactory = new OpISubNodeFactory());
            Add(OpFSubNodeFactory = new OpFSubNodeFactory());
            Add(OpIMulNodeFactory = new OpIMulNodeFactory());
            Add(OpFMulNodeFactory = new OpFMulNodeFactory());
            Add(OpUDivNodeFactory = new OpUDivNodeFactory());
            Add(OpSDivNodeFactory = new OpSDivNodeFactory());
            Add(OpFDivNodeFactory = new OpFDivNodeFactory());
            Add(OpUModNodeFactory = new OpUModNodeFactory());
            Add(OpSRemNodeFactory = new OpSRemNodeFactory());
            Add(OpSModNodeFactory = new OpSModNodeFactory());
            Add(OpFRemNodeFactory = new OpFRemNodeFactory());
            Add(OpFModNodeFactory = new OpFModNodeFactory());
            Add(OpVectorTimesScalarNodeFactory = new OpVectorTimesScalarNodeFactory());
            Add(OpMatrixTimesScalarNodeFactory = new OpMatrixTimesScalarNodeFactory());
            Add(OpVectorTimesMatrixNodeFactory = new OpVectorTimesMatrixNodeFactory());
            Add(OpMatrixTimesVectorNodeFactory = new OpMatrixTimesVectorNodeFactory());
            Add(OpMatrixTimesMatrixNodeFactory = new OpMatrixTimesMatrixNodeFactory());
            Add(OpOuterProductNodeFactory = new OpOuterProductNodeFactory());
            Add(OpDotNodeFactory = new OpDotNodeFactory());
            Add(OpIAddCarryNodeFactory = new OpIAddCarryNodeFactory());
            Add(OpISubBorrowNodeFactory = new OpISubBorrowNodeFactory());
            Add(OpUMulExtendedNodeFactory = new OpUMulExtendedNodeFactory());
            Add(OpSMulExtendedNodeFactory = new OpSMulExtendedNodeFactory());
            Add(OpAnyNodeFactory = new OpAnyNodeFactory());
            Add(OpAllNodeFactory = new OpAllNodeFactory());
            Add(OpIsNanNodeFactory = new OpIsNanNodeFactory());
            Add(OpIsInfNodeFactory = new OpIsInfNodeFactory());
            Add(OpIsFiniteNodeFactory = new OpIsFiniteNodeFactory());
            Add(OpIsNormalNodeFactory = new OpIsNormalNodeFactory());
            Add(OpSignBitSetNodeFactory = new OpSignBitSetNodeFactory());
            Add(OpLessOrGreaterNodeFactory = new OpLessOrGreaterNodeFactory());
            Add(OpOrderedNodeFactory = new OpOrderedNodeFactory());
            Add(OpUnorderedNodeFactory = new OpUnorderedNodeFactory());
            Add(OpLogicalEqualNodeFactory = new OpLogicalEqualNodeFactory());
            Add(OpLogicalNotEqualNodeFactory = new OpLogicalNotEqualNodeFactory());
            Add(OpLogicalOrNodeFactory = new OpLogicalOrNodeFactory());
            Add(OpLogicalAndNodeFactory = new OpLogicalAndNodeFactory());
            Add(OpLogicalNotNodeFactory = new OpLogicalNotNodeFactory());
            Add(OpSelectNodeFactory = new OpSelectNodeFactory());
            Add(OpIEqualNodeFactory = new OpIEqualNodeFactory());
            Add(OpINotEqualNodeFactory = new OpINotEqualNodeFactory());
            Add(OpUGreaterThanNodeFactory = new OpUGreaterThanNodeFactory());
            Add(OpSGreaterThanNodeFactory = new OpSGreaterThanNodeFactory());
            Add(OpUGreaterThanEqualNodeFactory = new OpUGreaterThanEqualNodeFactory());
            Add(OpSGreaterThanEqualNodeFactory = new OpSGreaterThanEqualNodeFactory());
            Add(OpULessThanNodeFactory = new OpULessThanNodeFactory());
            Add(OpSLessThanNodeFactory = new OpSLessThanNodeFactory());
            Add(OpULessThanEqualNodeFactory = new OpULessThanEqualNodeFactory());
            Add(OpSLessThanEqualNodeFactory = new OpSLessThanEqualNodeFactory());
            Add(OpFOrdEqualNodeFactory = new OpFOrdEqualNodeFactory());
            Add(OpFUnordEqualNodeFactory = new OpFUnordEqualNodeFactory());
            Add(OpFOrdNotEqualNodeFactory = new OpFOrdNotEqualNodeFactory());
            Add(OpFUnordNotEqualNodeFactory = new OpFUnordNotEqualNodeFactory());
            Add(OpFOrdLessThanNodeFactory = new OpFOrdLessThanNodeFactory());
            Add(OpFUnordLessThanNodeFactory = new OpFUnordLessThanNodeFactory());
            Add(OpFOrdGreaterThanNodeFactory = new OpFOrdGreaterThanNodeFactory());
            Add(OpFUnordGreaterThanNodeFactory = new OpFUnordGreaterThanNodeFactory());
            Add(OpFOrdLessThanEqualNodeFactory = new OpFOrdLessThanEqualNodeFactory());
            Add(OpFUnordLessThanEqualNodeFactory = new OpFUnordLessThanEqualNodeFactory());
            Add(OpFOrdGreaterThanEqualNodeFactory = new OpFOrdGreaterThanEqualNodeFactory());
            Add(OpFUnordGreaterThanEqualNodeFactory = new OpFUnordGreaterThanEqualNodeFactory());
            Add(OpShiftRightLogicalNodeFactory = new OpShiftRightLogicalNodeFactory());
            Add(OpShiftRightArithmeticNodeFactory = new OpShiftRightArithmeticNodeFactory());
            Add(OpShiftLeftLogicalNodeFactory = new OpShiftLeftLogicalNodeFactory());
            Add(OpBitwiseOrNodeFactory = new OpBitwiseOrNodeFactory());
            Add(OpBitwiseXorNodeFactory = new OpBitwiseXorNodeFactory());
            Add(OpBitwiseAndNodeFactory = new OpBitwiseAndNodeFactory());
            Add(OpNotNodeFactory = new OpNotNodeFactory());
            Add(OpBitFieldInsertNodeFactory = new OpBitFieldInsertNodeFactory());
            Add(OpBitFieldSExtractNodeFactory = new OpBitFieldSExtractNodeFactory());
            Add(OpBitFieldUExtractNodeFactory = new OpBitFieldUExtractNodeFactory());
            Add(OpBitReverseNodeFactory = new OpBitReverseNodeFactory());
            Add(OpBitCountNodeFactory = new OpBitCountNodeFactory());
            Add(OpDPdxNodeFactory = new OpDPdxNodeFactory());
            Add(OpDPdyNodeFactory = new OpDPdyNodeFactory());
            Add(OpFwidthNodeFactory = new OpFwidthNodeFactory());
            Add(OpDPdxFineNodeFactory = new OpDPdxFineNodeFactory());
            Add(OpDPdyFineNodeFactory = new OpDPdyFineNodeFactory());
            Add(OpFwidthFineNodeFactory = new OpFwidthFineNodeFactory());
            Add(OpDPdxCoarseNodeFactory = new OpDPdxCoarseNodeFactory());
            Add(OpDPdyCoarseNodeFactory = new OpDPdyCoarseNodeFactory());
            Add(OpFwidthCoarseNodeFactory = new OpFwidthCoarseNodeFactory());
            Add(OpEmitVertexNodeFactory = new OpEmitVertexNodeFactory());
            Add(OpEndPrimitiveNodeFactory = new OpEndPrimitiveNodeFactory());
            Add(OpEmitStreamVertexNodeFactory = new OpEmitStreamVertexNodeFactory());
            Add(OpEndStreamPrimitiveNodeFactory = new OpEndStreamPrimitiveNodeFactory());
            Add(OpControlBarrierNodeFactory = new OpControlBarrierNodeFactory());
            Add(OpMemoryBarrierNodeFactory = new OpMemoryBarrierNodeFactory());
            Add(OpAtomicLoadNodeFactory = new OpAtomicLoadNodeFactory());
            Add(OpAtomicStoreNodeFactory = new OpAtomicStoreNodeFactory());
            Add(OpAtomicExchangeNodeFactory = new OpAtomicExchangeNodeFactory());
            Add(OpAtomicCompareExchangeNodeFactory = new OpAtomicCompareExchangeNodeFactory());
            Add(OpAtomicCompareExchangeWeakNodeFactory = new OpAtomicCompareExchangeWeakNodeFactory());
            Add(OpAtomicIIncrementNodeFactory = new OpAtomicIIncrementNodeFactory());
            Add(OpAtomicIDecrementNodeFactory = new OpAtomicIDecrementNodeFactory());
            Add(OpAtomicIAddNodeFactory = new OpAtomicIAddNodeFactory());
            Add(OpAtomicISubNodeFactory = new OpAtomicISubNodeFactory());
            Add(OpAtomicSMinNodeFactory = new OpAtomicSMinNodeFactory());
            Add(OpAtomicUMinNodeFactory = new OpAtomicUMinNodeFactory());
            Add(OpAtomicSMaxNodeFactory = new OpAtomicSMaxNodeFactory());
            Add(OpAtomicUMaxNodeFactory = new OpAtomicUMaxNodeFactory());
            Add(OpAtomicAndNodeFactory = new OpAtomicAndNodeFactory());
            Add(OpAtomicOrNodeFactory = new OpAtomicOrNodeFactory());
            Add(OpAtomicXorNodeFactory = new OpAtomicXorNodeFactory());
            Add(OpPhiNodeFactory = new OpPhiNodeFactory());
            Add(OpLoopMergeNodeFactory = new OpLoopMergeNodeFactory());
            Add(OpSelectionMergeNodeFactory = new OpSelectionMergeNodeFactory());
            Add(OpLabelNodeFactory = new OpLabelNodeFactory());
            Add(OpBranchNodeFactory = new OpBranchNodeFactory());
            Add(OpBranchConditionalNodeFactory = new OpBranchConditionalNodeFactory());
            Add(OpSwitchNodeFactory = new OpSwitchNodeFactory());
            Add(OpKillNodeFactory = new OpKillNodeFactory());
            Add(OpReturnNodeFactory = new OpReturnNodeFactory());
            Add(OpReturnValueNodeFactory = new OpReturnValueNodeFactory());
            Add(OpUnreachableNodeFactory = new OpUnreachableNodeFactory());
            Add(OpLifetimeStartNodeFactory = new OpLifetimeStartNodeFactory());
            Add(OpLifetimeStopNodeFactory = new OpLifetimeStopNodeFactory());
            Add(OpGroupAsyncCopyNodeFactory = new OpGroupAsyncCopyNodeFactory());
            Add(OpGroupWaitEventsNodeFactory = new OpGroupWaitEventsNodeFactory());
            Add(OpGroupAllNodeFactory = new OpGroupAllNodeFactory());
            Add(OpGroupAnyNodeFactory = new OpGroupAnyNodeFactory());
            Add(OpGroupBroadcastNodeFactory = new OpGroupBroadcastNodeFactory());
            Add(OpGroupIAddNodeFactory = new OpGroupIAddNodeFactory());
            Add(OpGroupFAddNodeFactory = new OpGroupFAddNodeFactory());
            Add(OpGroupFMinNodeFactory = new OpGroupFMinNodeFactory());
            Add(OpGroupUMinNodeFactory = new OpGroupUMinNodeFactory());
            Add(OpGroupSMinNodeFactory = new OpGroupSMinNodeFactory());
            Add(OpGroupFMaxNodeFactory = new OpGroupFMaxNodeFactory());
            Add(OpGroupUMaxNodeFactory = new OpGroupUMaxNodeFactory());
            Add(OpGroupSMaxNodeFactory = new OpGroupSMaxNodeFactory());
            Add(OpReadPipeNodeFactory = new OpReadPipeNodeFactory());
            Add(OpWritePipeNodeFactory = new OpWritePipeNodeFactory());
            Add(OpReservedReadPipeNodeFactory = new OpReservedReadPipeNodeFactory());
            Add(OpReservedWritePipeNodeFactory = new OpReservedWritePipeNodeFactory());
            Add(OpReserveReadPipePacketsNodeFactory = new OpReserveReadPipePacketsNodeFactory());
            Add(OpReserveWritePipePacketsNodeFactory = new OpReserveWritePipePacketsNodeFactory());
            Add(OpCommitReadPipeNodeFactory = new OpCommitReadPipeNodeFactory());
            Add(OpCommitWritePipeNodeFactory = new OpCommitWritePipeNodeFactory());
            Add(OpIsValidReserveIdNodeFactory = new OpIsValidReserveIdNodeFactory());
            Add(OpGetNumPipePacketsNodeFactory = new OpGetNumPipePacketsNodeFactory());
            Add(OpGetMaxPipePacketsNodeFactory = new OpGetMaxPipePacketsNodeFactory());
            Add(OpGroupReserveReadPipePacketsNodeFactory = new OpGroupReserveReadPipePacketsNodeFactory());
            Add(OpGroupReserveWritePipePacketsNodeFactory = new OpGroupReserveWritePipePacketsNodeFactory());
            Add(OpGroupCommitReadPipeNodeFactory = new OpGroupCommitReadPipeNodeFactory());
            Add(OpGroupCommitWritePipeNodeFactory = new OpGroupCommitWritePipeNodeFactory());
            Add(OpEnqueueMarkerNodeFactory = new OpEnqueueMarkerNodeFactory());
            Add(OpEnqueueKernelNodeFactory = new OpEnqueueKernelNodeFactory());
            Add(OpGetKernelNDrangeSubGroupCountNodeFactory = new OpGetKernelNDrangeSubGroupCountNodeFactory());
            Add(OpGetKernelNDrangeMaxSubGroupSizeNodeFactory = new OpGetKernelNDrangeMaxSubGroupSizeNodeFactory());
            Add(OpGetKernelWorkGroupSizeNodeFactory = new OpGetKernelWorkGroupSizeNodeFactory());
            Add(OpGetKernelPreferredWorkGroupSizeMultipleNodeFactory = new OpGetKernelPreferredWorkGroupSizeMultipleNodeFactory());
            Add(OpRetainEventNodeFactory = new OpRetainEventNodeFactory());
            Add(OpReleaseEventNodeFactory = new OpReleaseEventNodeFactory());
            Add(OpCreateUserEventNodeFactory = new OpCreateUserEventNodeFactory());
            Add(OpIsValidEventNodeFactory = new OpIsValidEventNodeFactory());
            Add(OpSetUserEventStatusNodeFactory = new OpSetUserEventStatusNodeFactory());
            Add(OpCaptureEventProfilingInfoNodeFactory = new OpCaptureEventProfilingInfoNodeFactory());
            Add(OpGetDefaultQueueNodeFactory = new OpGetDefaultQueueNodeFactory());
            Add(OpBuildNDRangeNodeFactory = new OpBuildNDRangeNodeFactory());
            Add(OpImageSparseSampleImplicitLodNodeFactory = new OpImageSparseSampleImplicitLodNodeFactory());
            Add(OpImageSparseSampleExplicitLodNodeFactory = new OpImageSparseSampleExplicitLodNodeFactory());
            Add(OpImageSparseSampleDrefImplicitLodNodeFactory = new OpImageSparseSampleDrefImplicitLodNodeFactory());
            Add(OpImageSparseSampleDrefExplicitLodNodeFactory = new OpImageSparseSampleDrefExplicitLodNodeFactory());
            Add(OpImageSparseSampleProjImplicitLodNodeFactory = new OpImageSparseSampleProjImplicitLodNodeFactory());
            Add(OpImageSparseSampleProjExplicitLodNodeFactory = new OpImageSparseSampleProjExplicitLodNodeFactory());
            Add(OpImageSparseSampleProjDrefImplicitLodNodeFactory = new OpImageSparseSampleProjDrefImplicitLodNodeFactory());
            Add(OpImageSparseSampleProjDrefExplicitLodNodeFactory = new OpImageSparseSampleProjDrefExplicitLodNodeFactory());
            Add(OpImageSparseFetchNodeFactory = new OpImageSparseFetchNodeFactory());
            Add(OpImageSparseGatherNodeFactory = new OpImageSparseGatherNodeFactory());
            Add(OpImageSparseDrefGatherNodeFactory = new OpImageSparseDrefGatherNodeFactory());
            Add(OpImageSparseTexelsResidentNodeFactory = new OpImageSparseTexelsResidentNodeFactory());
            Add(OpNoLineNodeFactory = new OpNoLineNodeFactory());
            Add(OpAtomicFlagTestAndSetNodeFactory = new OpAtomicFlagTestAndSetNodeFactory());
            Add(OpAtomicFlagClearNodeFactory = new OpAtomicFlagClearNodeFactory());
            Add(OpImageSparseReadNodeFactory = new OpImageSparseReadNodeFactory());
            Add(OpDecorateIdNodeFactory = new OpDecorateIdNodeFactory());
            Add(OpSubgroupBallotKHRNodeFactory = new OpSubgroupBallotKHRNodeFactory());
            Add(OpSubgroupFirstInvocationKHRNodeFactory = new OpSubgroupFirstInvocationKHRNodeFactory());
            Add(OpSubgroupAllKHRNodeFactory = new OpSubgroupAllKHRNodeFactory());
            Add(OpSubgroupAnyKHRNodeFactory = new OpSubgroupAnyKHRNodeFactory());
            Add(OpSubgroupAllEqualKHRNodeFactory = new OpSubgroupAllEqualKHRNodeFactory());
            Add(OpSubgroupReadInvocationKHRNodeFactory = new OpSubgroupReadInvocationKHRNodeFactory());
            Add(OpGroupIAddNonUniformAMDNodeFactory = new OpGroupIAddNonUniformAMDNodeFactory());
            Add(OpGroupFAddNonUniformAMDNodeFactory = new OpGroupFAddNonUniformAMDNodeFactory());
            Add(OpGroupFMinNonUniformAMDNodeFactory = new OpGroupFMinNonUniformAMDNodeFactory());
            Add(OpGroupUMinNonUniformAMDNodeFactory = new OpGroupUMinNonUniformAMDNodeFactory());
            Add(OpGroupSMinNonUniformAMDNodeFactory = new OpGroupSMinNonUniformAMDNodeFactory());
            Add(OpGroupFMaxNonUniformAMDNodeFactory = new OpGroupFMaxNonUniformAMDNodeFactory());
            Add(OpGroupUMaxNonUniformAMDNodeFactory = new OpGroupUMaxNonUniformAMDNodeFactory());
            Add(OpGroupSMaxNonUniformAMDNodeFactory = new OpGroupSMaxNonUniformAMDNodeFactory());
            Add(OpFragmentMaskFetchAMDNodeFactory = new OpFragmentMaskFetchAMDNodeFactory());
            Add(OpFragmentFetchAMDNodeFactory = new OpFragmentFetchAMDNodeFactory());
            Add(OpSubgroupShuffleINTELNodeFactory = new OpSubgroupShuffleINTELNodeFactory());
            Add(OpSubgroupShuffleDownINTELNodeFactory = new OpSubgroupShuffleDownINTELNodeFactory());
            Add(OpSubgroupShuffleUpINTELNodeFactory = new OpSubgroupShuffleUpINTELNodeFactory());
            Add(OpSubgroupShuffleXorINTELNodeFactory = new OpSubgroupShuffleXorINTELNodeFactory());
            Add(OpSubgroupBlockReadINTELNodeFactory = new OpSubgroupBlockReadINTELNodeFactory());
            Add(OpSubgroupBlockWriteINTELNodeFactory = new OpSubgroupBlockWriteINTELNodeFactory());
            Add(OpSubgroupImageBlockReadINTELNodeFactory = new OpSubgroupImageBlockReadINTELNodeFactory());
            Add(OpSubgroupImageBlockWriteINTELNodeFactory = new OpSubgroupImageBlockWriteINTELNodeFactory());
            Add(OpDecorateStringGOOGLENodeFactory = new OpDecorateStringGOOGLENodeFactory());
            Add(OpMemberDecorateStringGOOGLENodeFactory = new OpMemberDecorateStringGOOGLENodeFactory());
        }

        public INodeFactory Resolve(Spv.Op op)
        {
            switch (op)
            {

                case Op.OpNop: return OpNopNodeFactory;
                case Op.OpUndef: return OpUndefNodeFactory;
                case Op.OpSourceContinued: return OpSourceContinuedNodeFactory;
                case Op.OpSource: return OpSourceNodeFactory;
                case Op.OpSourceExtension: return OpSourceExtensionNodeFactory;
                case Op.OpName: return OpNameNodeFactory;
                case Op.OpMemberName: return OpMemberNameNodeFactory;
                case Op.OpString: return OpStringNodeFactory;
                case Op.OpLine: return OpLineNodeFactory;
                case Op.OpExtension: return OpExtensionNodeFactory;
                case Op.OpExtInstImport: return OpExtInstImportNodeFactory;
                case Op.OpExtInst: return OpExtInstNodeFactory;
                case Op.OpMemoryModel: return OpMemoryModelNodeFactory;
                case Op.OpEntryPoint: return OpEntryPointNodeFactory;
                case Op.OpExecutionMode: return OpExecutionModeNodeFactory;
                case Op.OpCapability: return OpCapabilityNodeFactory;
                case Op.OpTypeVoid: return OpTypeVoidNodeFactory;
                case Op.OpTypeBool: return OpTypeBoolNodeFactory;
                case Op.OpTypeInt: return OpTypeIntNodeFactory;
                case Op.OpTypeFloat: return OpTypeFloatNodeFactory;
                case Op.OpTypeVector: return OpTypeVectorNodeFactory;
                case Op.OpTypeMatrix: return OpTypeMatrixNodeFactory;
                case Op.OpTypeImage: return OpTypeImageNodeFactory;
                case Op.OpTypeSampler: return OpTypeSamplerNodeFactory;
                case Op.OpTypeSampledImage: return OpTypeSampledImageNodeFactory;
                case Op.OpTypeArray: return OpTypeArrayNodeFactory;
                case Op.OpTypeRuntimeArray: return OpTypeRuntimeArrayNodeFactory;
                case Op.OpTypeStruct: return OpTypeStructNodeFactory;
                case Op.OpTypeOpaque: return OpTypeOpaqueNodeFactory;
                case Op.OpTypePointer: return OpTypePointerNodeFactory;
                case Op.OpTypeFunction: return OpTypeFunctionNodeFactory;
                case Op.OpTypeEvent: return OpTypeEventNodeFactory;
                case Op.OpTypeDeviceEvent: return OpTypeDeviceEventNodeFactory;
                case Op.OpTypeReserveId: return OpTypeReserveIdNodeFactory;
                case Op.OpTypeQueue: return OpTypeQueueNodeFactory;
                case Op.OpTypePipe: return OpTypePipeNodeFactory;
                case Op.OpTypeForwardPointer: return OpTypeForwardPointerNodeFactory;
                case Op.OpConstantTrue: return OpConstantTrueNodeFactory;
                case Op.OpConstantFalse: return OpConstantFalseNodeFactory;
                case Op.OpConstant: return OpConstantNodeFactory;
                case Op.OpConstantComposite: return OpConstantCompositeNodeFactory;
                case Op.OpConstantSampler: return OpConstantSamplerNodeFactory;
                case Op.OpConstantNull: return OpConstantNullNodeFactory;
                case Op.OpSpecConstantTrue: return OpSpecConstantTrueNodeFactory;
                case Op.OpSpecConstantFalse: return OpSpecConstantFalseNodeFactory;
                case Op.OpSpecConstant: return OpSpecConstantNodeFactory;
                case Op.OpSpecConstantComposite: return OpSpecConstantCompositeNodeFactory;
                case Op.OpSpecConstantOp: return OpSpecConstantOpNodeFactory;
                case Op.OpFunction: return OpFunctionNodeFactory;
                case Op.OpFunctionParameter: return OpFunctionParameterNodeFactory;
                case Op.OpFunctionEnd: return OpFunctionEndNodeFactory;
                case Op.OpFunctionCall: return OpFunctionCallNodeFactory;
                case Op.OpVariable: return OpVariableNodeFactory;
                case Op.OpImageTexelPointer: return OpImageTexelPointerNodeFactory;
                case Op.OpLoad: return OpLoadNodeFactory;
                case Op.OpStore: return OpStoreNodeFactory;
                case Op.OpCopyMemory: return OpCopyMemoryNodeFactory;
                case Op.OpCopyMemorySized: return OpCopyMemorySizedNodeFactory;
                case Op.OpAccessChain: return OpAccessChainNodeFactory;
                case Op.OpInBoundsAccessChain: return OpInBoundsAccessChainNodeFactory;
                case Op.OpPtrAccessChain: return OpPtrAccessChainNodeFactory;
                case Op.OpArrayLength: return OpArrayLengthNodeFactory;
                case Op.OpGenericPtrMemSemantics: return OpGenericPtrMemSemanticsNodeFactory;
                case Op.OpInBoundsPtrAccessChain: return OpInBoundsPtrAccessChainNodeFactory;
                case Op.OpDecorate: return OpDecorateNodeFactory;
                case Op.OpMemberDecorate: return OpMemberDecorateNodeFactory;
                case Op.OpDecorationGroup: return OpDecorationGroupNodeFactory;
                case Op.OpGroupDecorate: return OpGroupDecorateNodeFactory;
                case Op.OpGroupMemberDecorate: return OpGroupMemberDecorateNodeFactory;
                case Op.OpVectorExtractDynamic: return OpVectorExtractDynamicNodeFactory;
                case Op.OpVectorInsertDynamic: return OpVectorInsertDynamicNodeFactory;
                case Op.OpVectorShuffle: return OpVectorShuffleNodeFactory;
                case Op.OpCompositeConstruct: return OpCompositeConstructNodeFactory;
                case Op.OpCompositeExtract: return OpCompositeExtractNodeFactory;
                case Op.OpCompositeInsert: return OpCompositeInsertNodeFactory;
                case Op.OpCopyObject: return OpCopyObjectNodeFactory;
                case Op.OpTranspose: return OpTransposeNodeFactory;
                case Op.OpSampledImage: return OpSampledImageNodeFactory;
                case Op.OpImageSampleImplicitLod: return OpImageSampleImplicitLodNodeFactory;
                case Op.OpImageSampleExplicitLod: return OpImageSampleExplicitLodNodeFactory;
                case Op.OpImageSampleDrefImplicitLod: return OpImageSampleDrefImplicitLodNodeFactory;
                case Op.OpImageSampleDrefExplicitLod: return OpImageSampleDrefExplicitLodNodeFactory;
                case Op.OpImageSampleProjImplicitLod: return OpImageSampleProjImplicitLodNodeFactory;
                case Op.OpImageSampleProjExplicitLod: return OpImageSampleProjExplicitLodNodeFactory;
                case Op.OpImageSampleProjDrefImplicitLod: return OpImageSampleProjDrefImplicitLodNodeFactory;
                case Op.OpImageSampleProjDrefExplicitLod: return OpImageSampleProjDrefExplicitLodNodeFactory;
                case Op.OpImageFetch: return OpImageFetchNodeFactory;
                case Op.OpImageGather: return OpImageGatherNodeFactory;
                case Op.OpImageDrefGather: return OpImageDrefGatherNodeFactory;
                case Op.OpImageRead: return OpImageReadNodeFactory;
                case Op.OpImageWrite: return OpImageWriteNodeFactory;
                case Op.OpImage: return OpImageNodeFactory;
                case Op.OpImageQueryFormat: return OpImageQueryFormatNodeFactory;
                case Op.OpImageQueryOrder: return OpImageQueryOrderNodeFactory;
                case Op.OpImageQuerySizeLod: return OpImageQuerySizeLodNodeFactory;
                case Op.OpImageQuerySize: return OpImageQuerySizeNodeFactory;
                case Op.OpImageQueryLod: return OpImageQueryLodNodeFactory;
                case Op.OpImageQueryLevels: return OpImageQueryLevelsNodeFactory;
                case Op.OpImageQuerySamples: return OpImageQuerySamplesNodeFactory;
                case Op.OpConvertFToU: return OpConvertFToUNodeFactory;
                case Op.OpConvertFToS: return OpConvertFToSNodeFactory;
                case Op.OpConvertSToF: return OpConvertSToFNodeFactory;
                case Op.OpConvertUToF: return OpConvertUToFNodeFactory;
                case Op.OpUConvert: return OpUConvertNodeFactory;
                case Op.OpSConvert: return OpSConvertNodeFactory;
                case Op.OpFConvert: return OpFConvertNodeFactory;
                case Op.OpQuantizeToF16: return OpQuantizeToF16NodeFactory;
                case Op.OpConvertPtrToU: return OpConvertPtrToUNodeFactory;
                case Op.OpSatConvertSToU: return OpSatConvertSToUNodeFactory;
                case Op.OpSatConvertUToS: return OpSatConvertUToSNodeFactory;
                case Op.OpConvertUToPtr: return OpConvertUToPtrNodeFactory;
                case Op.OpPtrCastToGeneric: return OpPtrCastToGenericNodeFactory;
                case Op.OpGenericCastToPtr: return OpGenericCastToPtrNodeFactory;
                case Op.OpGenericCastToPtrExplicit: return OpGenericCastToPtrExplicitNodeFactory;
                case Op.OpBitcast: return OpBitcastNodeFactory;
                case Op.OpSNegate: return OpSNegateNodeFactory;
                case Op.OpFNegate: return OpFNegateNodeFactory;
                case Op.OpIAdd: return OpIAddNodeFactory;
                case Op.OpFAdd: return OpFAddNodeFactory;
                case Op.OpISub: return OpISubNodeFactory;
                case Op.OpFSub: return OpFSubNodeFactory;
                case Op.OpIMul: return OpIMulNodeFactory;
                case Op.OpFMul: return OpFMulNodeFactory;
                case Op.OpUDiv: return OpUDivNodeFactory;
                case Op.OpSDiv: return OpSDivNodeFactory;
                case Op.OpFDiv: return OpFDivNodeFactory;
                case Op.OpUMod: return OpUModNodeFactory;
                case Op.OpSRem: return OpSRemNodeFactory;
                case Op.OpSMod: return OpSModNodeFactory;
                case Op.OpFRem: return OpFRemNodeFactory;
                case Op.OpFMod: return OpFModNodeFactory;
                case Op.OpVectorTimesScalar: return OpVectorTimesScalarNodeFactory;
                case Op.OpMatrixTimesScalar: return OpMatrixTimesScalarNodeFactory;
                case Op.OpVectorTimesMatrix: return OpVectorTimesMatrixNodeFactory;
                case Op.OpMatrixTimesVector: return OpMatrixTimesVectorNodeFactory;
                case Op.OpMatrixTimesMatrix: return OpMatrixTimesMatrixNodeFactory;
                case Op.OpOuterProduct: return OpOuterProductNodeFactory;
                case Op.OpDot: return OpDotNodeFactory;
                case Op.OpIAddCarry: return OpIAddCarryNodeFactory;
                case Op.OpISubBorrow: return OpISubBorrowNodeFactory;
                case Op.OpUMulExtended: return OpUMulExtendedNodeFactory;
                case Op.OpSMulExtended: return OpSMulExtendedNodeFactory;
                case Op.OpAny: return OpAnyNodeFactory;
                case Op.OpAll: return OpAllNodeFactory;
                case Op.OpIsNan: return OpIsNanNodeFactory;
                case Op.OpIsInf: return OpIsInfNodeFactory;
                case Op.OpIsFinite: return OpIsFiniteNodeFactory;
                case Op.OpIsNormal: return OpIsNormalNodeFactory;
                case Op.OpSignBitSet: return OpSignBitSetNodeFactory;
                case Op.OpLessOrGreater: return OpLessOrGreaterNodeFactory;
                case Op.OpOrdered: return OpOrderedNodeFactory;
                case Op.OpUnordered: return OpUnorderedNodeFactory;
                case Op.OpLogicalEqual: return OpLogicalEqualNodeFactory;
                case Op.OpLogicalNotEqual: return OpLogicalNotEqualNodeFactory;
                case Op.OpLogicalOr: return OpLogicalOrNodeFactory;
                case Op.OpLogicalAnd: return OpLogicalAndNodeFactory;
                case Op.OpLogicalNot: return OpLogicalNotNodeFactory;
                case Op.OpSelect: return OpSelectNodeFactory;
                case Op.OpIEqual: return OpIEqualNodeFactory;
                case Op.OpINotEqual: return OpINotEqualNodeFactory;
                case Op.OpUGreaterThan: return OpUGreaterThanNodeFactory;
                case Op.OpSGreaterThan: return OpSGreaterThanNodeFactory;
                case Op.OpUGreaterThanEqual: return OpUGreaterThanEqualNodeFactory;
                case Op.OpSGreaterThanEqual: return OpSGreaterThanEqualNodeFactory;
                case Op.OpULessThan: return OpULessThanNodeFactory;
                case Op.OpSLessThan: return OpSLessThanNodeFactory;
                case Op.OpULessThanEqual: return OpULessThanEqualNodeFactory;
                case Op.OpSLessThanEqual: return OpSLessThanEqualNodeFactory;
                case Op.OpFOrdEqual: return OpFOrdEqualNodeFactory;
                case Op.OpFUnordEqual: return OpFUnordEqualNodeFactory;
                case Op.OpFOrdNotEqual: return OpFOrdNotEqualNodeFactory;
                case Op.OpFUnordNotEqual: return OpFUnordNotEqualNodeFactory;
                case Op.OpFOrdLessThan: return OpFOrdLessThanNodeFactory;
                case Op.OpFUnordLessThan: return OpFUnordLessThanNodeFactory;
                case Op.OpFOrdGreaterThan: return OpFOrdGreaterThanNodeFactory;
                case Op.OpFUnordGreaterThan: return OpFUnordGreaterThanNodeFactory;
                case Op.OpFOrdLessThanEqual: return OpFOrdLessThanEqualNodeFactory;
                case Op.OpFUnordLessThanEqual: return OpFUnordLessThanEqualNodeFactory;
                case Op.OpFOrdGreaterThanEqual: return OpFOrdGreaterThanEqualNodeFactory;
                case Op.OpFUnordGreaterThanEqual: return OpFUnordGreaterThanEqualNodeFactory;
                case Op.OpShiftRightLogical: return OpShiftRightLogicalNodeFactory;
                case Op.OpShiftRightArithmetic: return OpShiftRightArithmeticNodeFactory;
                case Op.OpShiftLeftLogical: return OpShiftLeftLogicalNodeFactory;
                case Op.OpBitwiseOr: return OpBitwiseOrNodeFactory;
                case Op.OpBitwiseXor: return OpBitwiseXorNodeFactory;
                case Op.OpBitwiseAnd: return OpBitwiseAndNodeFactory;
                case Op.OpNot: return OpNotNodeFactory;
                case Op.OpBitFieldInsert: return OpBitFieldInsertNodeFactory;
                case Op.OpBitFieldSExtract: return OpBitFieldSExtractNodeFactory;
                case Op.OpBitFieldUExtract: return OpBitFieldUExtractNodeFactory;
                case Op.OpBitReverse: return OpBitReverseNodeFactory;
                case Op.OpBitCount: return OpBitCountNodeFactory;
                case Op.OpDPdx: return OpDPdxNodeFactory;
                case Op.OpDPdy: return OpDPdyNodeFactory;
                case Op.OpFwidth: return OpFwidthNodeFactory;
                case Op.OpDPdxFine: return OpDPdxFineNodeFactory;
                case Op.OpDPdyFine: return OpDPdyFineNodeFactory;
                case Op.OpFwidthFine: return OpFwidthFineNodeFactory;
                case Op.OpDPdxCoarse: return OpDPdxCoarseNodeFactory;
                case Op.OpDPdyCoarse: return OpDPdyCoarseNodeFactory;
                case Op.OpFwidthCoarse: return OpFwidthCoarseNodeFactory;
                case Op.OpEmitVertex: return OpEmitVertexNodeFactory;
                case Op.OpEndPrimitive: return OpEndPrimitiveNodeFactory;
                case Op.OpEmitStreamVertex: return OpEmitStreamVertexNodeFactory;
                case Op.OpEndStreamPrimitive: return OpEndStreamPrimitiveNodeFactory;
                case Op.OpControlBarrier: return OpControlBarrierNodeFactory;
                case Op.OpMemoryBarrier: return OpMemoryBarrierNodeFactory;
                case Op.OpAtomicLoad: return OpAtomicLoadNodeFactory;
                case Op.OpAtomicStore: return OpAtomicStoreNodeFactory;
                case Op.OpAtomicExchange: return OpAtomicExchangeNodeFactory;
                case Op.OpAtomicCompareExchange: return OpAtomicCompareExchangeNodeFactory;
                case Op.OpAtomicCompareExchangeWeak: return OpAtomicCompareExchangeWeakNodeFactory;
                case Op.OpAtomicIIncrement: return OpAtomicIIncrementNodeFactory;
                case Op.OpAtomicIDecrement: return OpAtomicIDecrementNodeFactory;
                case Op.OpAtomicIAdd: return OpAtomicIAddNodeFactory;
                case Op.OpAtomicISub: return OpAtomicISubNodeFactory;
                case Op.OpAtomicSMin: return OpAtomicSMinNodeFactory;
                case Op.OpAtomicUMin: return OpAtomicUMinNodeFactory;
                case Op.OpAtomicSMax: return OpAtomicSMaxNodeFactory;
                case Op.OpAtomicUMax: return OpAtomicUMaxNodeFactory;
                case Op.OpAtomicAnd: return OpAtomicAndNodeFactory;
                case Op.OpAtomicOr: return OpAtomicOrNodeFactory;
                case Op.OpAtomicXor: return OpAtomicXorNodeFactory;
                case Op.OpPhi: return OpPhiNodeFactory;
                case Op.OpLoopMerge: return OpLoopMergeNodeFactory;
                case Op.OpSelectionMerge: return OpSelectionMergeNodeFactory;
                case Op.OpLabel: return OpLabelNodeFactory;
                case Op.OpBranch: return OpBranchNodeFactory;
                case Op.OpBranchConditional: return OpBranchConditionalNodeFactory;
                case Op.OpSwitch: return OpSwitchNodeFactory;
                case Op.OpKill: return OpKillNodeFactory;
                case Op.OpReturn: return OpReturnNodeFactory;
                case Op.OpReturnValue: return OpReturnValueNodeFactory;
                case Op.OpUnreachable: return OpUnreachableNodeFactory;
                case Op.OpLifetimeStart: return OpLifetimeStartNodeFactory;
                case Op.OpLifetimeStop: return OpLifetimeStopNodeFactory;
                case Op.OpGroupAsyncCopy: return OpGroupAsyncCopyNodeFactory;
                case Op.OpGroupWaitEvents: return OpGroupWaitEventsNodeFactory;
                case Op.OpGroupAll: return OpGroupAllNodeFactory;
                case Op.OpGroupAny: return OpGroupAnyNodeFactory;
                case Op.OpGroupBroadcast: return OpGroupBroadcastNodeFactory;
                case Op.OpGroupIAdd: return OpGroupIAddNodeFactory;
                case Op.OpGroupFAdd: return OpGroupFAddNodeFactory;
                case Op.OpGroupFMin: return OpGroupFMinNodeFactory;
                case Op.OpGroupUMin: return OpGroupUMinNodeFactory;
                case Op.OpGroupSMin: return OpGroupSMinNodeFactory;
                case Op.OpGroupFMax: return OpGroupFMaxNodeFactory;
                case Op.OpGroupUMax: return OpGroupUMaxNodeFactory;
                case Op.OpGroupSMax: return OpGroupSMaxNodeFactory;
                case Op.OpReadPipe: return OpReadPipeNodeFactory;
                case Op.OpWritePipe: return OpWritePipeNodeFactory;
                case Op.OpReservedReadPipe: return OpReservedReadPipeNodeFactory;
                case Op.OpReservedWritePipe: return OpReservedWritePipeNodeFactory;
                case Op.OpReserveReadPipePackets: return OpReserveReadPipePacketsNodeFactory;
                case Op.OpReserveWritePipePackets: return OpReserveWritePipePacketsNodeFactory;
                case Op.OpCommitReadPipe: return OpCommitReadPipeNodeFactory;
                case Op.OpCommitWritePipe: return OpCommitWritePipeNodeFactory;
                case Op.OpIsValidReserveId: return OpIsValidReserveIdNodeFactory;
                case Op.OpGetNumPipePackets: return OpGetNumPipePacketsNodeFactory;
                case Op.OpGetMaxPipePackets: return OpGetMaxPipePacketsNodeFactory;
                case Op.OpGroupReserveReadPipePackets: return OpGroupReserveReadPipePacketsNodeFactory;
                case Op.OpGroupReserveWritePipePackets: return OpGroupReserveWritePipePacketsNodeFactory;
                case Op.OpGroupCommitReadPipe: return OpGroupCommitReadPipeNodeFactory;
                case Op.OpGroupCommitWritePipe: return OpGroupCommitWritePipeNodeFactory;
                case Op.OpEnqueueMarker: return OpEnqueueMarkerNodeFactory;
                case Op.OpEnqueueKernel: return OpEnqueueKernelNodeFactory;
                case Op.OpGetKernelNDrangeSubGroupCount: return OpGetKernelNDrangeSubGroupCountNodeFactory;
                case Op.OpGetKernelNDrangeMaxSubGroupSize: return OpGetKernelNDrangeMaxSubGroupSizeNodeFactory;
                case Op.OpGetKernelWorkGroupSize: return OpGetKernelWorkGroupSizeNodeFactory;
                case Op.OpGetKernelPreferredWorkGroupSizeMultiple: return OpGetKernelPreferredWorkGroupSizeMultipleNodeFactory;
                case Op.OpRetainEvent: return OpRetainEventNodeFactory;
                case Op.OpReleaseEvent: return OpReleaseEventNodeFactory;
                case Op.OpCreateUserEvent: return OpCreateUserEventNodeFactory;
                case Op.OpIsValidEvent: return OpIsValidEventNodeFactory;
                case Op.OpSetUserEventStatus: return OpSetUserEventStatusNodeFactory;
                case Op.OpCaptureEventProfilingInfo: return OpCaptureEventProfilingInfoNodeFactory;
                case Op.OpGetDefaultQueue: return OpGetDefaultQueueNodeFactory;
                case Op.OpBuildNDRange: return OpBuildNDRangeNodeFactory;
                case Op.OpImageSparseSampleImplicitLod: return OpImageSparseSampleImplicitLodNodeFactory;
                case Op.OpImageSparseSampleExplicitLod: return OpImageSparseSampleExplicitLodNodeFactory;
                case Op.OpImageSparseSampleDrefImplicitLod: return OpImageSparseSampleDrefImplicitLodNodeFactory;
                case Op.OpImageSparseSampleDrefExplicitLod: return OpImageSparseSampleDrefExplicitLodNodeFactory;
                case Op.OpImageSparseSampleProjImplicitLod: return OpImageSparseSampleProjImplicitLodNodeFactory;
                case Op.OpImageSparseSampleProjExplicitLod: return OpImageSparseSampleProjExplicitLodNodeFactory;
                case Op.OpImageSparseSampleProjDrefImplicitLod: return OpImageSparseSampleProjDrefImplicitLodNodeFactory;
                case Op.OpImageSparseSampleProjDrefExplicitLod: return OpImageSparseSampleProjDrefExplicitLodNodeFactory;
                case Op.OpImageSparseFetch: return OpImageSparseFetchNodeFactory;
                case Op.OpImageSparseGather: return OpImageSparseGatherNodeFactory;
                case Op.OpImageSparseDrefGather: return OpImageSparseDrefGatherNodeFactory;
                case Op.OpImageSparseTexelsResident: return OpImageSparseTexelsResidentNodeFactory;
                case Op.OpNoLine: return OpNoLineNodeFactory;
                case Op.OpAtomicFlagTestAndSet: return OpAtomicFlagTestAndSetNodeFactory;
                case Op.OpAtomicFlagClear: return OpAtomicFlagClearNodeFactory;
                case Op.OpImageSparseRead: return OpImageSparseReadNodeFactory;
                case Op.OpDecorateId: return OpDecorateIdNodeFactory;
                case Op.OpSubgroupBallotKHR: return OpSubgroupBallotKHRNodeFactory;
                case Op.OpSubgroupFirstInvocationKHR: return OpSubgroupFirstInvocationKHRNodeFactory;
                case Op.OpSubgroupAllKHR: return OpSubgroupAllKHRNodeFactory;
                case Op.OpSubgroupAnyKHR: return OpSubgroupAnyKHRNodeFactory;
                case Op.OpSubgroupAllEqualKHR: return OpSubgroupAllEqualKHRNodeFactory;
                case Op.OpSubgroupReadInvocationKHR: return OpSubgroupReadInvocationKHRNodeFactory;
                case Op.OpGroupIAddNonUniformAMD: return OpGroupIAddNonUniformAMDNodeFactory;
                case Op.OpGroupFAddNonUniformAMD: return OpGroupFAddNonUniformAMDNodeFactory;
                case Op.OpGroupFMinNonUniformAMD: return OpGroupFMinNonUniformAMDNodeFactory;
                case Op.OpGroupUMinNonUniformAMD: return OpGroupUMinNonUniformAMDNodeFactory;
                case Op.OpGroupSMinNonUniformAMD: return OpGroupSMinNonUniformAMDNodeFactory;
                case Op.OpGroupFMaxNonUniformAMD: return OpGroupFMaxNonUniformAMDNodeFactory;
                case Op.OpGroupUMaxNonUniformAMD: return OpGroupUMaxNonUniformAMDNodeFactory;
                case Op.OpGroupSMaxNonUniformAMD: return OpGroupSMaxNonUniformAMDNodeFactory;
                case Op.OpFragmentMaskFetchAMD: return OpFragmentMaskFetchAMDNodeFactory;
                case Op.OpFragmentFetchAMD: return OpFragmentFetchAMDNodeFactory;
                case Op.OpSubgroupShuffleINTEL: return OpSubgroupShuffleINTELNodeFactory;
                case Op.OpSubgroupShuffleDownINTEL: return OpSubgroupShuffleDownINTELNodeFactory;
                case Op.OpSubgroupShuffleUpINTEL: return OpSubgroupShuffleUpINTELNodeFactory;
                case Op.OpSubgroupShuffleXorINTEL: return OpSubgroupShuffleXorINTELNodeFactory;
                case Op.OpSubgroupBlockReadINTEL: return OpSubgroupBlockReadINTELNodeFactory;
                case Op.OpSubgroupBlockWriteINTEL: return OpSubgroupBlockWriteINTELNodeFactory;
                case Op.OpSubgroupImageBlockReadINTEL: return OpSubgroupImageBlockReadINTELNodeFactory;
                case Op.OpSubgroupImageBlockWriteINTEL: return OpSubgroupImageBlockWriteINTELNodeFactory;
                case Op.OpDecorateStringGOOGLE: return OpDecorateStringGOOGLENodeFactory;
                case Op.OpMemberDecorateStringGOOGLE: return OpMemberDecorateStringGOOGLENodeFactory;
            }
            throw new NotImplementedException(op.ToString());
        }
    }
}