// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SpirVCodeGen
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class EnumTemplate : EnumTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System.Collections.Generic;\r\n\r\nnamespace SpirVGraph.Spv\r\n{\r\n    public part" +
                    "ial class ");
            
            #line 10 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write(" : ValueEnum\r\n    {\r\n        public enum Enumerant\r\n        {\r\n");
            
            #line 14 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"

		foreach (var kv in Values)
		{
			foreach (var capability in kv.capabilities ?? EmptyReadOnlyList<string>.Instance)
			{

            
            #line default
            #line hidden
            this.Write("            [Capability(Capability.Enumerant.");
            
            #line 20 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(capability));
            
            #line default
            #line hidden
            this.Write(")]\r\n");
            
            #line 21 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"

			}

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 24 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetId(kv.enumerant)));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 24 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kv.value));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 25 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n");
            
            #line 30 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"

		foreach (var kv in Values)
		{
			if (kv.parameters != null && kv.parameters.Count > 0)
			{

            
            #line default
            #line hidden
            this.Write("        public class ");
            
            #line 36 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetId(kv.enumerant)));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 36 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            public ");
            
            #line 38 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetId(kv.enumerant)));
            
            #line default
            #line hidden
            this.Write("():base(Enumerant.");
            
            #line 38 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetId(kv.enumerant)));
            
            #line default
            #line hidden
            this.Write("){}\r\n");
            
            #line 39 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"

		foreach (var parameter in kv.parameters)
		{

            
            #line default
            #line hidden
            this.Write("            public ");
            
            #line 43 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetParameterType(parameter.kind)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 43 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetName(GetId(kv.enumerant), parameter)));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 44 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"

		}

            
            #line default
            #line hidden
            this.Write("            public new static ");
            
            #line 47 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetId(kv.enumerant)));
            
            #line default
            #line hidden
            this.Write(" Parse(WordReader reader, uint wordCount)\r\n            {\r\n\t\t\t\tvar end = reader.Po" +
                    "sition+wordCount;\r\n                var res = new ");
            
            #line 50 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetId(kv.enumerant)));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 51 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"

		foreach (var parameter in kv.parameters)
		{

            
            #line default
            #line hidden
            this.Write("                res.");
            
            #line 55 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetName(GetId(kv.enumerant), parameter)));
            
            #line default
            #line hidden
            this.Write(" = Spv.");
            
            #line 55 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.kind));
            
            #line default
            #line hidden
            this.Write(".Parse(reader, end-reader.Position);\r\n");
            
            #line 56 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"

		}

            
            #line default
            #line hidden
            this.Write("                return res;\r\n            }\r\n        }\r\n");
            
            #line 62 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"

			}
		}

            
            #line default
            #line hidden
            this.Write("\r\n        public ");
            
            #line 67 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("(Enumerant value)\r\n        {\r\n            Value = value;\r\n        }\r\n\r\n        pu" +
                    "blic Enumerant Value { get; }\r\n\r\n        public static ");
            
            #line 74 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write(" Parse(WordReader reader, uint wordCount)\r\n        {\r\n            var id = (Enume" +
                    "rant) reader.ReadWord();\r\n            switch (id)\r\n            {\r\n");
            
            #line 79 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"

		foreach (var kv in Values)
		{
			if (kv.parameters != null && kv.parameters.Count > 0)
			{

            
            #line default
            #line hidden
            this.Write("                case Enumerant.");
            
            #line 85 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetId(kv.enumerant)));
            
            #line default
            #line hidden
            this.Write(" :\r\n                    return ");
            
            #line 86 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetId(kv.enumerant)));
            
            #line default
            #line hidden
            this.Write(".Parse(reader, wordCount - 1);\r\n");
            
            #line 87 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"

			}
		}

            
            #line default
            #line hidden
            this.Write("                default:\r\n                    return new ");
            
            #line 92 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("(id);\r\n            }\r\n        }\r\n\t\t\r\n        public static ");
            
            #line 96 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write(" ParseOptional(WordReader reader, uint wordCount)\r\n        {\r\n\t\t\tif (wordCount ==" +
                    " 0) return null;\r\n            return Parse(reader, wordCount);\r\n        }\r\n\r\n   " +
                    "     public static IList<");
            
            #line 102 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("> ParseCollection(WordReader reader, uint wordCount)\r\n        {\r\n            var " +
                    "end = reader.Position + wordCount;\r\n            var res = new PrintableList<");
            
            #line 105 "E:\MyWork\SpirVisualEditor\src\SpirVCodeGen\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write(@">();
            while (reader.Position < end)
            {
                res.Add(Parse(reader, end-reader.Position));
            }
            return res;
        }

        public override string ToString()
        {
            return Value.ToString();
        }
    }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class EnumTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
